config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'home#index'

  get 'login/new', as: :login

  resources :events, only: [:index, :show]
  resources :blog_posts, only: [:index, :show]

  resources :profiles

  resources :wods, only: [:index, :show]

  namespace :admin do
    root 'dashboard#index'
    resources :dashboard, only: :index
      get 'dashboard/wods_index', to: 'dashboard#wods_index', as: :wods_index


    resources :blog_posts, except: :destroy
    resources :wods, except: [:show, :destroy]
  end
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id         :integer          not null, primary key
#  title      :string
#  user_id    :integer
#  body       :text
#  summary    :string
#  created_at :datetime
#  updated_at :datetime
#  pub_status :string
#  featured   :boolean
#

class BlogPost < ActiveRecord::Base
  belongs_to :user

  validates :title, :summary, :body, :pub_status, presence: :true

  def author
    if user.try(:profile)
      user.profile.first_name + " " + user.profile.last_name
    else
      "Predator Camp HQ"
    end
  end
end

app/controllers/admin/blog_posts_controller.rb
module Admin
  class BlogPostsController < BaseController
    def index
      @blog_posts = BlogPost.all
    end

    def new
      @blog_post = BlogPost.new
    end

    def create
      @blog_post = BlogPost.create(blog_params)
      if @blog_post.save
        flash[:notice] = "Blog post was create."
        redirect_to edit_admin_blog_post_path(@blog_post)
      else
        flash[:alert] = "Blog post could not be created."
        render :new
      end
    end

    def edit
      @blog_post = BlogPost.find(params[:id])
    end

    def update
      @blog_post = BlogPost.find(params[:id])
      if @blog_post.update(blog_params)
        flash[:notice] = "Success, blog post was updated."
        redirect_to edit_admin_blog_post_path(@blog_post)
      else
        flash[:alert] = "Blog could not be updated."
        render :edit
      end
    end

    private

    def blog_params
      params.require(:blog_post).permit(:title, :user_id, :body, :summary, :pub_status)
    end
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blogs = BlogPost.all
  end

  def show
    @blog = BlogPost.find(params[:id])
  end
end

app/views/blog_posts/index.html.erb
<% @blogs.each do |blog| %>
  <div class="blog--row">
    <div class="box--blog">
      <div class="blog--hero">
        <%= link_to blog_post_path(blog) do %>
          <p class="blog--title"><%= blog.title %></p>
          <p class="blog--author">By: <%= blog.author %></p>
          <p class="blog--summary"><%= blog.summary %></p>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/blog_posts/show.html.erb
<div class="container">
  <div class="container--blog">
    <p class="blog--title__show"><%= @blog.title %></p>
    <p class="blog--body"><%= raw(@blog.body) %></p>
  </div>
</div>