config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  root 'home#index'

  get 'login/new', as: :login

  resources :events, only: [:index, :show]
  resources :blog_posts, only: [:index, :show]

  resources :profiles

  resources :wods, only: [:index, :show]

  namespace :admin do
    root 'dashboard#index'
    resources :dashboard, only: :index
      get 'dashboard/wods_index', to: 'dashboard#wods_index', as: :wods_index


    resources :blog_posts, except: :destroy
    resources :wods, except: [:show, :destroy]
  end
end

app/models/blog_post.rb
# == Schema Information
#
# Table name: blog_posts
#
#  id         :integer          not null, primary key
#  title      :string
#  user_id    :integer
#  body       :text
#  summary    :string
#  created_at :datetime
#  updated_at :datetime
#  pub_status :string
#  featured   :boolean
#

class BlogPost < ActiveRecord::Base
  belongs_to :user

  validates :title, :summary, :body, :pub_status, presence: :true

  def author
    if user.try(:profile)
      user.profile.first_name + " " + user.profile.last_name
    else
      "Predator Camp HQ"
    end
  end
end

app/models/constant.rb
class Constant
  PUB_OPTIONS = [["Publish", "p"], ["Draft", "d"], ["Archive", "a"]]
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id           :integer          not null, primary key
#  firstname    :string
#  lastname     :string
#  age          :integer
#  yearshunting :integer
#  huntingstyle :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  user_id      :integer
#

class Profile < ActiveRecord::Base
  belongs_to :user

  HUNTING_METHODS = ["Rifle", "Archery", "Muzzleloader", "Spear"]

  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :age, presence: true
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id            :integer          not null, primary key
#  name          :string
#  resource_id   :integer
#  resource_type :string
#  created_at    :datetime
#  updated_at    :datetime
#

class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles

  belongs_to :resource,
             :polymorphic => true
             # :optional => true  ##only supported in rails 5+

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string
#  last_sign_in_ip        :string
#  confirmation_token     :string
#  confirmed_at           :datetime
#  confirmation_sent_at   :datetime
#  unconfirmed_email      :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#

class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
end

app/models/wod.rb
# == Schema Information
#
# Table name: wods
#
#  id           :integer          not null, primary key
#  duration     :string
#  workout_type :string
#  workout      :text
#  created_at   :datetime
#  updated_at   :datetime
#  title        :string
#  workout_date :string
#  pub_status   :string
#  start_time   :datetime
#

class Wod < ActiveRecord::Base
  validates :title,
            :duration,
            :workout_type,
            :workout,
            :workout_date,
            :pub_status, presence: true

  WORKOUT_TYPES = [ "Strength", "MetCon", "Run / RuckRun", "Dry Fire", "Live Fire", "Hero" ]
  REST_DAY = "Rest and Recover today, if you're tired, relax, otherwise you can do a light recovery walk, strech, or ride."

  def convert_to_start_time
    unless workout_date.blank?
      date = workout_date.gsub("/", "-")
      year = date.last(4)
      date.slice!(5..10)
      new_date = year + "-" + date
      self.start_time = new_date.to_date
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :resource_name, :resource, :devise_mapping

  protected

  def resource_name
   :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :firstname, :lastname, :phone]
    devise_parameter_sanitizer.for(:account_update) << [:name, :firstname, :lastname, :image, :phone]
  end
end

app/controllers/base_controller.rb
class BaseController < ApplicationController
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  def index
    @blogs = BlogPost.all
  end

  def show
    @blog = BlogPost.find(params[:id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @wods = Wod.all
  end
end

app/controllers/home_controller.rb
class HomeController < BaseController
  def index
    if current_user
      @wod = Wod.find_by(start_time: Time.zone.now.beginning_of_day).nil? ? Wod::REST_DAY : Wod.find_by(start_time: Time.zone.now.beginning_of_day)
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def new
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

  def show
    @profile = Profile.find(params[:id])
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = current_user

    if @profile.save
      flash[:notice] = "Profile was saved"
      redirect_to @profile
    else
      flash.now[:alert] = "There was an error saving profile"
      render :new
    end
  end

  def edit
    @profile = Profile.find(params[:id])
  end

  def update
    @profile = Profile.find(params[:id])
    @profile.assign_attributes(profile_params)

    if @profile.save
      flash[:notice] = "Profile was updated"
      redirect_to @profile

      flash.now[:alert] = "There was an error updating profile"
      render :new
    end
  end

  def destroy
    @profile = Profile.find(params[:id])

    if @profile.destroy
      flash[:notice] = "\"#{@profile.firstname} #{@profile.lastname}\"\'s\ profile has been deleted"
      redirect_to root_path
    else
      flash.now[:alert] = "There was an error deleting that profile"
    end
  end

end

private

def profile_params
  params.require(:profile).permit(:firstname, :lastname, :age)
end

app/controllers/wods_controller.rb
class WodsController < ApplicationController
  def show
    @wod = Wod.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_helper.rb
module BlogHelper
  def color_class(i)
    if i%2 == 0
      "ocean-blue"
    elsif i%2 == 1
      "purple-grey"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/nav_helper.rb
module NavHelper
  def current_page(path)
    "current" if current_page?(path)
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/wods_helper.rb
module WodsHelper
end

app/views/layouts/admin/dashboard_base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render "shared/meta_tags" %>
  </head>
  <body>

    <div class="container">
      <%= render "shared/header" %>
    </div>

    <main class="container">
      <%= render "shared/flashes" %>
        <%= render "shared/admin/navblock" %>
      <div class="container">
        <%= yield %>
      </div>
    </main>
  </body>
</html>

app/views/shared/_flashes.html.erb
<div class="container">
  <% if flash[:notice] %>
    <div class="notice">
      <%= flash[:notice] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert">
      <%= flash.now[:alert] %>
    </div>
  <% end %>
</div>

app/views/shared/_header.html.erb
<div class="container">
  <%# if current_user %>
    <%= render "shared/nav" %>
  <%# else %>
    <%#= render "shared/user_nav" %>
  <%# end %>
</div>

app/views/shared/_meta_tags.html.erb
    <title>PredatorCamp</title>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>

app/views/shared/_nav.html.erb
<%
  events_current = current_page(events_path)
  blog_current = current_page(blog_posts_path)
  home_current = current_page(root_path)
  login_current = current_page(login_path)
  admin_current = current_page(admin_dashboard_index_path) ||
                  current_page(admin_blog_posts_path) ||
                  current_page(admin_root_path) ||
                  current_page(admin_wods_index_path)
%>

<div class="container--nav__bar">
  <div class="row">
    <div class="fourcol nav__logo">
      <%= link_to root_path do %>
        <%= image_tag "pc.png", alt: "predator camp PC logo", class: "nav__logo--image" %>
        <div class="nav__logo--title-box">
          <p class="nav__logo--title">
            Predator Camp
          </p>
          <p class="nav__logo--subtitle">
            Conditioning, Knowlege, Preparation
          </p>
        </div>
      <% end %>
    </div>
    <div class="eightcol container--nav__links last">

      <%# if current_user %>
        <%= link_to "CALENDAR", events_path, class: "nav__link #{events_current}" %>
      <%# else %>
        <%#= link_to "HOME", root_path, class: "nav__link #{home_current}" %>
      <%# end %>
      <%= link_to "BLOG", blog_posts_path, class: "nav__link #{blog_current}" %>
      <%= link_to "PROFILE", "#", class: "nav__link" %>
      <% if current_user %>
        <%= link_to "SIGNOUT", destroy_user_session_path, method: :delete, class: "nav__link" %>
      <% else %>
        <%= link_to "SIGNIN / REGISTER", login_path, class: "nav__link #{login_current}" %>
      <% end %>
      <% if current_user && current_user.has_role?(:admin) %>
        <%= link_to "ADMIN", admin_dashboard_index_path, class: "nav__link #{admin_current}" %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_user_nav.html.erb
<div class="container--nav__bar">
  <div class="row">
      <div class="fourcol logo">
        MY BIG FAT LOGO
      </div>
      <div class="twocol nav__link">
        a link
      </div>
      <div class="twocol nav__link">
        a link
      </div>
      <div class="twocol nav__link">
        a link
      </div>
  </div>
</div>

app/views/shared/admin/_navblock.html.erb
<%
  # events_current = current_page(events_path)
  blog_current = current_page(admin_dashboard_index_path)
  wod_current = current_page(admin_wods_index_path)
%>

<div class="container">
  <div class="row">
    <div class="threecol">
      <div class="block">
        <%= link_to admin_dashboard_index_path do %>
          <%= image_tag "blog-icon.png", alt: "blog icon", class: "admin--nav__icon" %>
        <% end %>
      </div>
      <% if blog_current %>
        <%= link_to "New Post", new_admin_blog_post_path, class: "btn dashboard" %>
      <% end %>
    </div>

    <div class="threecol">
      <div class="block">
        <%= link_to admin_wods_index_path do %>
          <%= image_tag "wod-icon.png", alt: "blog icon", class: "admin--nav__icon" %>
        <% end %>
      </div>
      <% if wod_current %>
        <%= link_to "New WOD", new_admin_wod_path, class: "btn dashboard" %>
      <% end %>
    </div>

    <div class="block threecol">
      <%= image_tag "bounty-hunter.png", alt: "blog icon", class: "admin--nav__icon" %>
    </div>

    <div class="block threecol last">
      <%= image_tag "calendar-icon.png", alt: "blog icon", class: "admin--nav__icon" %>
    </div>
  </div>
</div>